### ISSUE TITLE
Combat system:

### ISSUE THREAD

**Issue by KrzysiekZakrzewski** [KrzysiekZakrzewski/SuperCow---Mutant-Adventure#4]
1. UI:
- button to select abilities 
- Progress bar 
- health bar 
2. Atack:
- player or enemy can miss atack
- deal random damage (random.rage)
3. fight results:
- if player win get reward 
- if player loss comeback to checkpoint and loss exp and item

**Comment by KrzysiekZakrzewski** [comment]
Start project a scene combat and UI:
Name, health, mana

**Comment by KrzysiekZakrzewski** [comment]
StatsUI - Complete
Creat ScriptableObject to creat skills, basic attack and enemy stats
Player can attack enemy and end turn 
Start creat enemy turn and AI

**Comment by PawelSocha1989** [comment]
Implement AnimatorController to CombatScene.

**Comment by KrzysiekZakrzewski** [comment]
Add rewards if player win and reduction stats if loss
